version: '3'

services:
  mongo_db:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 4000:5000
    environment:
      DOCKDB_NAME: dockerTWO
      PORT: 5000
      MONDB_URI: mongodb://mongo_db:27017/dockerTWO
      
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
